import React from "react";
import { useOutletContext } from "react-router-dom";
import { useMockStore } from "../../data/mockStore.jsx";

export default function Notification() {
  const { darkMode } = useOutletContext();
  const { getNotificationsForCurrentUser, markNotificationRead } =
    useMockStore();
  const notifications = getNotificationsForCurrentUser();
  return (
    <div
      className={`p-5 md:p-6 lg:p-8 max-w-[1000px] mx-auto ${
        darkMode ? "text-slate-100" : "text-slate-900"
      }`}
    >
      <div className="mb-6">
        <p className="text-xs uppercase tracking-widest font-bold text-slate-400">
          Student Portal
        </p>
        <h1 className="text-2xl font-black">Notifications</h1>
        <p className="text-sm mt-1 text-slate-500">
          Updates are generated by shared application, document, assignment, and
          evaluation actions.
        </p>
      </div>
      <section className="border border-slate-200 rounded-2xl overflow-hidden bg-white">
        {notifications.length === 0 ? (
          <p className="p-6 text-sm text-slate-500">No notifications yet.</p>
        ) : (
          <div className="divide-y divide-slate-200">
            {notifications.map((notification) => (
              <button
                key={notification.id}
                className={`w-full text-left p-5 ${
                  notification.readAt ? "opacity-60" : ""
                }`}
                onClick={() => markNotificationRead(notification.id)}
              >
                <div className="flex justify-between gap-4">
                  <strong className="text-sm">{notification.title}</strong>
                  <span className="text-[10px] text-slate-400">
                    {new Date(notification.createdAt).toLocaleString()}
                  </span>
                </div>
                <p className="text-xs text-slate-500 mt-2">
                  {notification.message}
                </p>
                <p className="text-[10px] text-slate-400 mt-2">
                  {notification.relatedEntityType}:
                  {notification.relatedEntityId} ·{" "}
                  {notification.readAt ? "Read" : "Unread"}
                </p>
              </button>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
