import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../../supabaseClient";

const ResetPassword = () => {
  const navigate = useNavigate();

  // =========================================================
  // FORM
  // =========================================================

  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const [loading, setLoading] = useState(false);
  const [checkingSession, setCheckingSession] = useState(true);

  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  // =========================================================
  // CHECK RECOVERY SESSION
  // =========================================================

  useEffect(() => {
    let mounted = true;

    const checkSession = async () => {
      try {
        // =====================================================
        // IMPORTANT:
        //
        // The recovery link generated by Supabase establishes
        // a temporary authenticated recovery session.
        //
        // Since password recovery is no longer role-based,
        // we use the common Supabase client here.
        // =====================================================

        const {
          data: { session },
          error: sessionError,
        } = await supabase.auth.getSession();

        if (!mounted) {
          return;
        }

        if (sessionError) {
          console.error("Password recovery session error:", sessionError);

          setError("Unable to verify your password recovery session.");

          return;
        }

        if (!session) {
          setError(
            "This password reset link is invalid, expired, or has already been used."
          );

          return;
        }

        // =====================================================
        // RECOVERY SESSION VERIFIED
        // =====================================================

        console.log("Password recovery session verified:", {
          email: session.user?.email,
          userId: session.user?.id,
        });
      } catch (err) {
        console.error("Unexpected password recovery session error:", err);

        if (mounted) {
          setError("Unable to verify your password recovery session.");
        }
      } finally {
        if (mounted) {
          setCheckingSession(false);
        }
      }
    };

    checkSession();

    return () => {
      mounted = false;
    };
  }, []);

  // =========================================================
  // UPDATE PASSWORD
  // =========================================================

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (loading) {
      return;
    }

    setError("");
    setMessage("");

    // =======================================================
    // VALIDATION
    // =======================================================

    if (!password || !confirmPassword) {
      setError("Please enter and confirm your password.");
      return;
    }

    if (password.length < 8) {
      setError("Password must be at least 8 characters long.");
      return;
    }

    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    try {
      setLoading(true);

      // =====================================================
      // VERIFY SESSION BEFORE UPDATING
      // =====================================================

      const {
        data: { session },
        error: sessionError,
      } = await supabase.auth.getSession();

      if (sessionError) {
        console.error("Recovery session verification error:", sessionError);

        setError("Unable to verify your password recovery session.");

        return;
      }

      if (!session) {
        setError(
          "This password reset session is invalid or has expired. Please request a new reset link."
        );

        return;
      }

      // =====================================================
      // UPDATE SUPABASE AUTH PASSWORD
      // =====================================================
      //
      // The recovery session authorizes this password change.
      //
      // No Edge Function is needed here.
      // =====================================================

      const { error: updateError } = await supabase.auth.updateUser({
        password,
      });

      if (updateError) {
        console.error("Password update error:", updateError);

        setError(updateError.message || "Unable to update your password.");

        return;
      }

      // =====================================================
      // SUCCESS
      // =====================================================

      setMessage(
        "Your password has been updated successfully. You can now log in."
      );

      setPassword("");
      setConfirmPassword("");

      // =====================================================
      // SIGN OUT RECOVERY SESSION
      // =====================================================
      //
      // The recovery session is no longer needed after the
      // password has been changed.
      // =====================================================

      const { error: signOutError } = await supabase.auth.signOut();

      if (signOutError) {
        console.warn("Recovery session sign-out warning:", signOutError);
      }

      // =====================================================
      // RETURN TO LOGIN
      // =====================================================

      setTimeout(() => {
        navigate("/login", {
          replace: true,
        });
      }, 2000);
    } catch (err) {
      console.error("Unexpected password update error:", err);

      setError("Something went wrong while updating your password.");
    } finally {
      setLoading(false);
    }
  };

  // =========================================================
  // LOADING SCREEN
  // =========================================================

  if (checkingSession) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-gray-100 to-gray-200 flex items-center justify-center px-4">
        <div className="bg-white rounded-2xl shadow-xl border border-slate-100 p-8 text-center max-w-md w-full">
          <div className="w-12 h-12 mx-auto mb-5 rounded-xl bg-slate-100 flex items-center justify-center">
            <svg
              className="w-6 h-6 text-slate-500 animate-spin"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              />

              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"
              />
            </svg>
          </div>

          <h2 className="text-xl font-bold text-slate-800">
            Verifying Reset Link
          </h2>

          <p className="text-sm text-slate-500 mt-2">
            Please wait while we verify your password recovery session.
          </p>
        </div>
      </div>
    );
  }

  // =========================================================
  // RENDER
  // =========================================================

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-gray-100 to-gray-200 font-sans text-gray-800 flex flex-col">
      <main className="flex-1 flex flex-col items-center justify-center py-20 px-4 w-full">
        <div className="w-full max-w-lg">
          {/* =================================================
              CARD
          ================================================= */}

          <div className="bg-white rounded-2xl p-8 md:p-10 shadow-xl border border-slate-100">
            {/* =================================================
                ICON
            ================================================= */}

            <div className="flex justify-center">
              <div className="w-16 h-16 rounded-2xl bg-slate-50 border border-slate-100 flex items-center justify-center mb-6 shadow-inner">
                <svg
                  className="w-8 h-8 text-slate-700"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
                  />
                </svg>
              </div>
            </div>

            <h1 className="text-2xl font-black tracking-tight text-slate-900 text-center">
              Reset Your Password
            </h1>

            <p className="text-sm text-slate-500 text-center mt-2 mb-8">
              Create a new password for your SIMS account.
            </p>

            {/* =================================================
                ERROR
            ================================================= */}

            {error && (
              <div className="mb-6 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">
                {error}
              </div>
            )}

            {/* =================================================
                SUCCESS
            ================================================= */}

            {message && (
              <div className="mb-6 rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">
                {message}
              </div>
            )}

            {/* =================================================
                FORM
            ================================================= */}

            {!error && !message && (
              <form onSubmit={handleSubmit} className="space-y-5">
                {/* NEW PASSWORD */}

                <div>
                  <label
                    htmlFor="new-password"
                    className="block text-[11px] font-bold uppercase tracking-wider text-slate-500 mb-1.5"
                  >
                    New Password
                  </label>

                  <input
                    id="new-password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Enter your new password"
                    autoComplete="new-password"
                    disabled={loading}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-800 focus:bg-white transition disabled:opacity-60"
                  />

                  <p className="text-[11px] text-slate-400 mt-1.5">
                    Password must be at least 8 characters.
                  </p>
                </div>

                {/* CONFIRM PASSWORD */}

                <div>
                  <label
                    htmlFor="confirm-password"
                    className="block text-[11px] font-bold uppercase tracking-wider text-slate-500 mb-1.5"
                  >
                    Confirm Password
                  </label>

                  <input
                    id="confirm-password"
                    type="password"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    placeholder="Confirm your new password"
                    autoComplete="new-password"
                    disabled={loading}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-800 focus:bg-white transition disabled:opacity-60"
                  />
                </div>

                {/* SUBMIT */}

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full bg-gradient-to-r from-slate-700 to-slate-900 text-white py-3 rounded-xl text-sm font-semibold tracking-wide shadow-sm hover:opacity-95 transition-all duration-200 cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
                >
                  {loading ? "Updating Password..." : "Update Password"}
                </button>
              </form>
            )}

            {/* =================================================
                ERROR → LOGIN
            ================================================= */}

            {error && (
              <button
                type="button"
                onClick={() =>
                  navigate("/login", {
                    replace: true,
                  })
                }
                className="w-full mt-4 py-3 rounded-xl border border-slate-200 bg-white text-slate-600 text-sm font-semibold hover:bg-slate-50 transition"
              >
                Back to Login
              </button>
            )}

            {/* =================================================
                SUCCESS → LOGIN
            ================================================= */}

            {message && (
              <button
                type="button"
                onClick={() =>
                  navigate("/login", {
                    replace: true,
                  })
                }
                className="w-full mt-4 py-3 rounded-xl border border-slate-200 bg-white text-slate-600 text-sm font-semibold hover:bg-slate-50 transition"
              >
                Back to Login
              </button>
            )}
          </div>

          {/* =================================================
              FOOTER
          ================================================= */}

          <div className="text-center mt-6">
            <p className="text-xs text-slate-400">
              © 2026 SIMS |{" "}
              <button
                type="button"
                onClick={() => navigate("/privacy")}
                className="hover:text-slate-700"
              >
                Privacy Policy
              </button>{" "}
              |{" "}
              <button
                type="button"
                onClick={() => navigate("/terms")}
                className="hover:text-slate-700"
              >
                Terms of Service
              </button>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default ResetPassword;
